nix/node-env.nix
I wanted to add some `buildInputs` and override `shellHook` on our shell environment, and without this patch I couldn't.
=> Make shell environment overridable

nix/node-env.nix
Also fix a warning from `find` about order of `maxdepth` and `type` arguments.
This makes it easier to run `nix-shell` for Node packages.
=> Use $PWD (Nix build root) as a home instead of TMPDIR

nix/node-env.nix
Also does some cleanup. This is because recently `stripHash` stopped to output its results into `strippedName` and instead echoes them (as expected from a Bash function).
=> Fix strippedName usage in composePackage

nix/node-env.nix
For some reason npm tries to download packages even when they are already there and (seemingly) already of required versions when npm-shrinkwrap is used.
This fixes https://github.com/NixOS/nixpkgs/issues/18652. Notice that I have no idea what am I doing! This may be a wrong fix which hides an actual problem somewhere.
=> Remove npm-shrinkwrap.json file when installing a package

nix/node-env.nix
This backports changes from https://github.com/NixOS/nixpkgs/commit/2de932188080586ec02e2eac4fee1581c38d247b to this repository. cc @FRidh.
=> Use nodejs's version of Python

nix/node-env.nix
Many scripts are run as hooks to this command
(https://docs.npmjs.com/misc/scripts), adding output which the install phase
will try to mv as files.
=> Ignore all but the last line of output from npm pack

nix/node-env.nix
Piping find into xargs doesn't work if there are nested directories (without the 'x' bit set) because find cannot enter the directory until after chmod is executed. This fixes the issue.
=> Fix adding x bit on nested directories.

nix/node-env.nix
Currently, npm package names are generated prefixed by "node-". This causes issues, because when parsing package names, nix stops at the first "-", expecting a version number to come afterwards. This causes nix to think all your npm packages are named "node", so every time you install a new npm package, all your old ones are removed (nix removes the package named "node", which because of this bug, includes all of them).
=> Fixes bug #110

nix/node-env.nix
In nixpkgs master we check for undefined variables now.
Also see: https://github.com/NixOS/nixpkgs/pull/79410/files#r376299414
=> node-env.nix: make it work with set -u

bin/node2nix.js, default.nix
https://github.com/NixOS/nixpkgs/pull/71799 introduced the `nodejs-13_x` package set support in Nixpkgs. We forgot to update `node2nix` in the process, hence this PR.
Tested this change in a local nixpkgs checkout with
`../result/bin/node2nix --nodejs-13 -i node-packages-v13.json -o node-packages-v13.nix -c composition-v13.nix `. The resulting files are correct.
Also: `nodejs-8_x` has been removed from the current nixpkgs master. Updating
the default nodejs package to `nodejs-10_x` in `default.nix`.
=> Add support for nixpkgs's nodejs-13_x packageset.

lib/sources/Source.js
Unauthenticated git:// protocol doesn't work on GitLab.com. See https://gitlab.com/gitlab-com/support-forum/issues/3225. Fixes #157.
=> Use HTTPS URL for GitLab

nix/node-env.nix
Signed-off-by: Tim Dysinger <tim@dysinger.net>
This variable ends up appearing verbatim in the shell script. It doesn't get substituted by nix without ${} around it. I think this a typo because the rest of your vars in this file have the proper decorations.
=> You have to use ${nodeDependencies} or substitution will not happen

nix/node-env.nix
This allows one to figure out which packages are causing evaluation
failures if ran with --show-trace
I just had to debug an evaluation failure, which was impossible without this.
Sidenote: The failure came from a `package-lock.json` file containing `resolved = false` fields, which seems to be [a bug in npm](https://npm.community/t/npm-install-or-npm-update-turns-a-bunch-of-resolved-in-package-lock-json-from-real-values-to-false/3308). This resulted in `fetchurl { url = false; ... }`, resulting in `error: illegal name: '.drv'`. I guess it wouldn't hurt if `fetchurl` gave a better error too, might PR that to nixpkgs.
=> Add package error context to composePackage

nix/node-env.nix
When creating packages with `node2nix -i node-packages.json` we can specify NodeJS version at CLI. However, it is never exposed in Nix, which makes certain inconveniences (I wanted to create another executable node script).
I was able to get `node` executable path inside builder with
```
NODE=$(readlink -f $(which node))
```
but it is less than ideal. The proposed solution allows to change that to
```
$nodejs/bin/node
"${package.nodejs}/bin/node"
```
=> buildNodePackage: expose nodejs

lib/expressions/CompositionExpression.js, lib/expressions/OutputExpression.js, lib/expressions/PackageExpression.js
This follows on my previous PR #199. In this PR, I override the `src` field for `nodeDependencies` so that it only depends on `package.json` and `package-lock.json`, if present. Thus, the dependencies don't have to be rebuilt unless there's a change to these two files. 
This works well for my use-case, where I generate the dependencies separately and then symlink them into my own derivation to build my app. This follows a suggestion from #74 and is a partial solution to that issue. 
I think this is a clear win for the `buildNodeDependencies` export. Whether it should also be used with `buildNodeShell`, `buildNodePackage`, etc. is less clear. It would speed up builds significantly and fix #74, but the discussion there mentions that symlinking `node_modules` might not always work. (For …
=> Make nodeDependencies depend only on package.json/package-lock.json

default.nix, lib/node2nix.js, node-packages.nix
Nixpkgs has a CI check that enforces this for Nix files. Currently,
there's an exception made for node2nix files, but it would be good if
that exception could be dropped and node2nix-generated files followed
the same rules as everything else.
=> End generated files with final newline

lib/expressions/PackageExpression.js, nix/node-env.nix
Nixpkgs is in the process of deprecating accessing the library via `stdenv` (https://github.com/NixOS/nixpkgs/issues/108938), this PR makes it so that node2nix does not generate `stdenv.lib`.
=> stdenv.lib -> lib

nix/node-env.nix
Keeping an empty platforms, causes to hydra to avoid caching in certain
platforms like darwin.
=> Set default meta.platforms of nodePackages to Node.js platforms

default.nix, lib/expressions/CompositionExpression.js, nix/node-env.nix
The installation logic is fairly generic, and only needs to know the
packageName and src. Using a shell function instead of interpolating
the variables into a repeated snippet reduces the derivation size
significantly.
Also factor out some repeated logic in includeDependencies.
As a motivating example, these two changes combined reduce the
derivation size of zigbee2mqtt from 3.2M to 690K.
---
Created in response to https://github.com/svanderburg/node2nix/issues/46#issuecomment-801378717
=> Extract common logic from composePackage to a shell function

nix/node-env.nix
The call to `npm rebuild` can bring in additional executable scripts
which need to be patched as well.
This relates to issue #184
=> Add a second call to patchShebangs to

lib/sources/Source.js
Unauthenticated git:// protocol doesn't work on GitHub. See
https://github.blog/2021-09-01-improving-git-protocol-security-github
=> Use HTTPS URL for GitHub

bin/node2nix.js, tests/cli/default.nix
Currently, `node2nix` accepts and silently ignores invalid options, which is confusing.
=> Reject invalid command-line options

lib/sources/Source.js
I encountered issues on Jan 11th last week during the [GitHub git:// protocol brownout](https://github.blog/2021-09-01-improving-git-protocol-security-github) due to the version spec `github:jean-emmanuel/bonjour` in [open-stage-control](https://github.com/jean-emmanuel/open-stage-control) being fetched as `git://github.com/jean-emmanuel/bonjour` rather than `https://github.com/jean-emmanuel/bonjour`. I traced it back to the URL getting rewritten to `https://github.com/jean-emmanuel/bonjour` by [Source.js](https://github.com/svanderburg/node2nix/blob/0deb18a/lib/sources/Source.js#L52-L53) but then subsequently rewritten while fetching to `git://github.com/jean-emmanuel/bonjour` by [GitSource.js](https://github.com/svanderburg/node2nix/blob/0deb18a/lib/sources/GitSource.js#L56-L69) as an …
=> Use git+https:// protocol for HTTPS git URLs

README.md
The only difference between `shell.nodeDependencies` and `nodeDependencies` in this example is that `shell.nodeDependencies` skips https://github.com/svanderburg/node2nix/pull/205 - but in the example given I think it's most likely that people only want the dependencies to depend on package{,-lock}.json.
This was introduced in https://github.com/svanderburg/node2nix/pull/218.
=> docs: Use nodeDependencies instead of shell.nodeDependencies

bin/node2nix.js, default.nix
Node.js 12.x has reached End-of-Life (https://nodejs.org/en/about/releases/) , so I think it would be good to switch default Node.js version to `nodejs-14_x`.
Thank you.
=> Upgrade default Node.js version to 14.x

bin/node2nix.js
This PR adds support for Node.js 18.x, just like the former versions. Some packages now require 18, so this can be important to some users.
=> Add nodejs-18 option

.gitignore, flake.lock, flake.nix
Add a `flake.nix` and `flake.lock` file so that `node2nix` can be used/addressed as a Nix Flake.
=> Flakeify node2nix

bin/node2nix.js, lib/Package.js, nix/node-env.nix
Lockfile v2 mostly just has a bit of extra metadata and all dependencies are hoisted to the top-level with path-specific keys in a new lock value called "packages". This update emits enough of the format that NPM v7+ seem to be happy enough with it and does not try to rewrite it and cause `ENOTCACHED` errors with the sandbox.
As of NPM v7+, it no longer links bins for the top-level project automatically unless a global install is selected<sup>[1]</sup> (and is not a problem specific to node2nix<sup>[2]</sup>). Given a global install would cause more problems than it would solve, I added a simple script to perform the linking ourselves and instructed `npm install` to never link them for consistency.
Additionally, this adds a `postRebuild` hook that can be used by packages to run extra …
=> Emit lockfile v2 and fix bin links with NPM v7+
